/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated/student'
import { Route as AuthenticatedSchoolRouteImport } from './routes/_authenticated/school'
import { Route as AuthenticatedGovRouteImport } from './routes/_authenticated/gov'
import { Route as AuthenticatedStudentIndexRouteImport } from './routes/_authenticated/student.index'
import { Route as AuthenticatedSchoolIndexRouteImport } from './routes/_authenticated/school.index'
import { Route as AuthenticatedGovIndexRouteImport } from './routes/_authenticated/gov.index'
import { Route as AuthenticatedStudentIdRouteImport } from './routes/_authenticated/student.id'
import { Route as AuthenticatedStudentApplicationsRouteImport } from './routes/_authenticated/student.applications'
import { Route as AuthenticatedSchoolStudentsRouteImport } from './routes/_authenticated/school.students'
import { Route as AuthenticatedSchoolSettingsRouteImport } from './routes/_authenticated/school.settings'
import { Route as AuthenticatedSchoolApplicationsRouteImport } from './routes/_authenticated/school.applications'
import { Route as AuthenticatedGovStudentsRouteImport } from './routes/_authenticated/gov.students'
import { Route as AuthenticatedGovSchoolsRouteImport } from './routes/_authenticated/gov.schools'
import { Route as AuthenticatedGovLogsRouteImport } from './routes/_authenticated/gov.logs'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchoolRoute = AuthenticatedSchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGovRoute = AuthenticatedGovRouteImport.update({
  id: '/gov',
  path: '/gov',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentIndexRoute =
  AuthenticatedStudentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedSchoolIndexRoute =
  AuthenticatedSchoolIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSchoolRoute,
  } as any)
const AuthenticatedGovIndexRoute = AuthenticatedGovIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedGovRoute,
} as any)
const AuthenticatedStudentIdRoute = AuthenticatedStudentIdRouteImport.update({
  id: '/id',
  path: '/id',
  getParentRoute: () => AuthenticatedStudentRoute,
} as any)
const AuthenticatedStudentApplicationsRoute =
  AuthenticatedStudentApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedSchoolStudentsRoute =
  AuthenticatedSchoolStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedSchoolRoute,
  } as any)
const AuthenticatedSchoolSettingsRoute =
  AuthenticatedSchoolSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedSchoolRoute,
  } as any)
const AuthenticatedSchoolApplicationsRoute =
  AuthenticatedSchoolApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedSchoolRoute,
  } as any)
const AuthenticatedGovStudentsRoute =
  AuthenticatedGovStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedGovRoute,
  } as any)
const AuthenticatedGovSchoolsRoute = AuthenticatedGovSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => AuthenticatedGovRoute,
} as any)
const AuthenticatedGovLogsRoute = AuthenticatedGovLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedGovRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/gov': typeof AuthenticatedGovRouteWithChildren
  '/school': typeof AuthenticatedSchoolRouteWithChildren
  '/student': typeof AuthenticatedStudentRouteWithChildren
  '/gov/logs': typeof AuthenticatedGovLogsRoute
  '/gov/schools': typeof AuthenticatedGovSchoolsRoute
  '/gov/students': typeof AuthenticatedGovStudentsRoute
  '/school/applications': typeof AuthenticatedSchoolApplicationsRoute
  '/school/settings': typeof AuthenticatedSchoolSettingsRoute
  '/school/students': typeof AuthenticatedSchoolStudentsRoute
  '/student/applications': typeof AuthenticatedStudentApplicationsRoute
  '/student/id': typeof AuthenticatedStudentIdRoute
  '/gov/': typeof AuthenticatedGovIndexRoute
  '/school/': typeof AuthenticatedSchoolIndexRoute
  '/student/': typeof AuthenticatedStudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/gov/logs': typeof AuthenticatedGovLogsRoute
  '/gov/schools': typeof AuthenticatedGovSchoolsRoute
  '/gov/students': typeof AuthenticatedGovStudentsRoute
  '/school/applications': typeof AuthenticatedSchoolApplicationsRoute
  '/school/settings': typeof AuthenticatedSchoolSettingsRoute
  '/school/students': typeof AuthenticatedSchoolStudentsRoute
  '/student/applications': typeof AuthenticatedStudentApplicationsRoute
  '/student/id': typeof AuthenticatedStudentIdRoute
  '/gov': typeof AuthenticatedGovIndexRoute
  '/school': typeof AuthenticatedSchoolIndexRoute
  '/student': typeof AuthenticatedStudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/gov': typeof AuthenticatedGovRouteWithChildren
  '/_authenticated/school': typeof AuthenticatedSchoolRouteWithChildren
  '/_authenticated/student': typeof AuthenticatedStudentRouteWithChildren
  '/_authenticated/gov/logs': typeof AuthenticatedGovLogsRoute
  '/_authenticated/gov/schools': typeof AuthenticatedGovSchoolsRoute
  '/_authenticated/gov/students': typeof AuthenticatedGovStudentsRoute
  '/_authenticated/school/applications': typeof AuthenticatedSchoolApplicationsRoute
  '/_authenticated/school/settings': typeof AuthenticatedSchoolSettingsRoute
  '/_authenticated/school/students': typeof AuthenticatedSchoolStudentsRoute
  '/_authenticated/student/applications': typeof AuthenticatedStudentApplicationsRoute
  '/_authenticated/student/id': typeof AuthenticatedStudentIdRoute
  '/_authenticated/gov/': typeof AuthenticatedGovIndexRoute
  '/_authenticated/school/': typeof AuthenticatedSchoolIndexRoute
  '/_authenticated/student/': typeof AuthenticatedStudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/search'
    | '/sitemap.xml'
    | '/gov'
    | '/school'
    | '/student'
    | '/gov/logs'
    | '/gov/schools'
    | '/gov/students'
    | '/school/applications'
    | '/school/settings'
    | '/school/students'
    | '/student/applications'
    | '/student/id'
    | '/gov/'
    | '/school/'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/search'
    | '/sitemap.xml'
    | '/gov/logs'
    | '/gov/schools'
    | '/gov/students'
    | '/school/applications'
    | '/school/settings'
    | '/school/students'
    | '/student/applications'
    | '/student/id'
    | '/gov'
    | '/school'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/search'
    | '/sitemap.xml'
    | '/_authenticated/gov'
    | '/_authenticated/school'
    | '/_authenticated/student'
    | '/_authenticated/gov/logs'
    | '/_authenticated/gov/schools'
    | '/_authenticated/gov/students'
    | '/_authenticated/school/applications'
    | '/_authenticated/school/settings'
    | '/_authenticated/school/students'
    | '/_authenticated/student/applications'
    | '/_authenticated/student/id'
    | '/_authenticated/gov/'
    | '/_authenticated/school/'
    | '/_authenticated/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/school': {
      id: '/_authenticated/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof AuthenticatedSchoolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gov': {
      id: '/_authenticated/gov'
      path: '/gov'
      fullPath: '/gov'
      preLoaderRoute: typeof AuthenticatedGovRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/': {
      id: '/_authenticated/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof AuthenticatedStudentIndexRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/school/': {
      id: '/_authenticated/school/'
      path: '/'
      fullPath: '/school/'
      preLoaderRoute: typeof AuthenticatedSchoolIndexRouteImport
      parentRoute: typeof AuthenticatedSchoolRoute
    }
    '/_authenticated/gov/': {
      id: '/_authenticated/gov/'
      path: '/'
      fullPath: '/gov/'
      preLoaderRoute: typeof AuthenticatedGovIndexRouteImport
      parentRoute: typeof AuthenticatedGovRoute
    }
    '/_authenticated/student/id': {
      id: '/_authenticated/student/id'
      path: '/id'
      fullPath: '/student/id'
      preLoaderRoute: typeof AuthenticatedStudentIdRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/applications': {
      id: '/_authenticated/student/applications'
      path: '/applications'
      fullPath: '/student/applications'
      preLoaderRoute: typeof AuthenticatedStudentApplicationsRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/school/students': {
      id: '/_authenticated/school/students'
      path: '/students'
      fullPath: '/school/students'
      preLoaderRoute: typeof AuthenticatedSchoolStudentsRouteImport
      parentRoute: typeof AuthenticatedSchoolRoute
    }
    '/_authenticated/school/settings': {
      id: '/_authenticated/school/settings'
      path: '/settings'
      fullPath: '/school/settings'
      preLoaderRoute: typeof AuthenticatedSchoolSettingsRouteImport
      parentRoute: typeof AuthenticatedSchoolRoute
    }
    '/_authenticated/school/applications': {
      id: '/_authenticated/school/applications'
      path: '/applications'
      fullPath: '/school/applications'
      preLoaderRoute: typeof AuthenticatedSchoolApplicationsRouteImport
      parentRoute: typeof AuthenticatedSchoolRoute
    }
    '/_authenticated/gov/students': {
      id: '/_authenticated/gov/students'
      path: '/students'
      fullPath: '/gov/students'
      preLoaderRoute: typeof AuthenticatedGovStudentsRouteImport
      parentRoute: typeof AuthenticatedGovRoute
    }
    '/_authenticated/gov/schools': {
      id: '/_authenticated/gov/schools'
      path: '/schools'
      fullPath: '/gov/schools'
      preLoaderRoute: typeof AuthenticatedGovSchoolsRouteImport
      parentRoute: typeof AuthenticatedGovRoute
    }
    '/_authenticated/gov/logs': {
      id: '/_authenticated/gov/logs'
      path: '/logs'
      fullPath: '/gov/logs'
      preLoaderRoute: typeof AuthenticatedGovLogsRouteImport
      parentRoute: typeof AuthenticatedGovRoute
    }
  }
}

interface AuthenticatedGovRouteChildren {
  AuthenticatedGovLogsRoute: typeof AuthenticatedGovLogsRoute
  AuthenticatedGovSchoolsRoute: typeof AuthenticatedGovSchoolsRoute
  AuthenticatedGovStudentsRoute: typeof AuthenticatedGovStudentsRoute
  AuthenticatedGovIndexRoute: typeof AuthenticatedGovIndexRoute
}

const AuthenticatedGovRouteChildren: AuthenticatedGovRouteChildren = {
  AuthenticatedGovLogsRoute: AuthenticatedGovLogsRoute,
  AuthenticatedGovSchoolsRoute: AuthenticatedGovSchoolsRoute,
  AuthenticatedGovStudentsRoute: AuthenticatedGovStudentsRoute,
  AuthenticatedGovIndexRoute: AuthenticatedGovIndexRoute,
}

const AuthenticatedGovRouteWithChildren =
  AuthenticatedGovRoute._addFileChildren(AuthenticatedGovRouteChildren)

interface AuthenticatedSchoolRouteChildren {
  AuthenticatedSchoolApplicationsRoute: typeof AuthenticatedSchoolApplicationsRoute
  AuthenticatedSchoolSettingsRoute: typeof AuthenticatedSchoolSettingsRoute
  AuthenticatedSchoolStudentsRoute: typeof AuthenticatedSchoolStudentsRoute
  AuthenticatedSchoolIndexRoute: typeof AuthenticatedSchoolIndexRoute
}

const AuthenticatedSchoolRouteChildren: AuthenticatedSchoolRouteChildren = {
  AuthenticatedSchoolApplicationsRoute: AuthenticatedSchoolApplicationsRoute,
  AuthenticatedSchoolSettingsRoute: AuthenticatedSchoolSettingsRoute,
  AuthenticatedSchoolStudentsRoute: AuthenticatedSchoolStudentsRoute,
  AuthenticatedSchoolIndexRoute: AuthenticatedSchoolIndexRoute,
}

const AuthenticatedSchoolRouteWithChildren =
  AuthenticatedSchoolRoute._addFileChildren(AuthenticatedSchoolRouteChildren)

interface AuthenticatedStudentRouteChildren {
  AuthenticatedStudentApplicationsRoute: typeof AuthenticatedStudentApplicationsRoute
  AuthenticatedStudentIdRoute: typeof AuthenticatedStudentIdRoute
  AuthenticatedStudentIndexRoute: typeof AuthenticatedStudentIndexRoute
}

const AuthenticatedStudentRouteChildren: AuthenticatedStudentRouteChildren = {
  AuthenticatedStudentApplicationsRoute: AuthenticatedStudentApplicationsRoute,
  AuthenticatedStudentIdRoute: AuthenticatedStudentIdRoute,
  AuthenticatedStudentIndexRoute: AuthenticatedStudentIndexRoute,
}

const AuthenticatedStudentRouteWithChildren =
  AuthenticatedStudentRoute._addFileChildren(AuthenticatedStudentRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGovRoute: typeof AuthenticatedGovRouteWithChildren
  AuthenticatedSchoolRoute: typeof AuthenticatedSchoolRouteWithChildren
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGovRoute: AuthenticatedGovRouteWithChildren,
  AuthenticatedSchoolRoute: AuthenticatedSchoolRouteWithChildren,
  AuthenticatedStudentRoute: AuthenticatedStudentRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
