/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated/student'
import { Route as AuthenticatedSchoolRouteImport } from './routes/_authenticated/school'
import { Route as AuthenticatedGovRouteImport } from './routes/_authenticated/gov'
import { Route as AuthenticatedGovIndexRouteImport } from './routes/_authenticated/gov.index'
import { Route as AuthenticatedGovStudentsRouteImport } from './routes/_authenticated/gov.students'
import { Route as AuthenticatedGovLogsRouteImport } from './routes/_authenticated/gov.logs'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchoolRoute = AuthenticatedSchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGovRoute = AuthenticatedGovRouteImport.update({
  id: '/gov',
  path: '/gov',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGovIndexRoute = AuthenticatedGovIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedGovRoute,
} as any)
const AuthenticatedGovStudentsRoute =
  AuthenticatedGovStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedGovRoute,
  } as any)
const AuthenticatedGovLogsRoute = AuthenticatedGovLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedGovRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/gov': typeof AuthenticatedGovRouteWithChildren
  '/school': typeof AuthenticatedSchoolRoute
  '/student': typeof AuthenticatedStudentRoute
  '/gov/logs': typeof AuthenticatedGovLogsRoute
  '/gov/students': typeof AuthenticatedGovStudentsRoute
  '/gov/': typeof AuthenticatedGovIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/school': typeof AuthenticatedSchoolRoute
  '/student': typeof AuthenticatedStudentRoute
  '/gov/logs': typeof AuthenticatedGovLogsRoute
  '/gov/students': typeof AuthenticatedGovStudentsRoute
  '/gov': typeof AuthenticatedGovIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/gov': typeof AuthenticatedGovRouteWithChildren
  '/_authenticated/school': typeof AuthenticatedSchoolRoute
  '/_authenticated/student': typeof AuthenticatedStudentRoute
  '/_authenticated/gov/logs': typeof AuthenticatedGovLogsRoute
  '/_authenticated/gov/students': typeof AuthenticatedGovStudentsRoute
  '/_authenticated/gov/': typeof AuthenticatedGovIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/gov'
    | '/school'
    | '/student'
    | '/gov/logs'
    | '/gov/students'
    | '/gov/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/school'
    | '/student'
    | '/gov/logs'
    | '/gov/students'
    | '/gov'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/gov'
    | '/_authenticated/school'
    | '/_authenticated/student'
    | '/_authenticated/gov/logs'
    | '/_authenticated/gov/students'
    | '/_authenticated/gov/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/school': {
      id: '/_authenticated/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof AuthenticatedSchoolRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gov': {
      id: '/_authenticated/gov'
      path: '/gov'
      fullPath: '/gov'
      preLoaderRoute: typeof AuthenticatedGovRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gov/': {
      id: '/_authenticated/gov/'
      path: '/'
      fullPath: '/gov/'
      preLoaderRoute: typeof AuthenticatedGovIndexRouteImport
      parentRoute: typeof AuthenticatedGovRoute
    }
    '/_authenticated/gov/students': {
      id: '/_authenticated/gov/students'
      path: '/students'
      fullPath: '/gov/students'
      preLoaderRoute: typeof AuthenticatedGovStudentsRouteImport
      parentRoute: typeof AuthenticatedGovRoute
    }
    '/_authenticated/gov/logs': {
      id: '/_authenticated/gov/logs'
      path: '/logs'
      fullPath: '/gov/logs'
      preLoaderRoute: typeof AuthenticatedGovLogsRouteImport
      parentRoute: typeof AuthenticatedGovRoute
    }
  }
}

interface AuthenticatedGovRouteChildren {
  AuthenticatedGovLogsRoute: typeof AuthenticatedGovLogsRoute
  AuthenticatedGovStudentsRoute: typeof AuthenticatedGovStudentsRoute
  AuthenticatedGovIndexRoute: typeof AuthenticatedGovIndexRoute
}

const AuthenticatedGovRouteChildren: AuthenticatedGovRouteChildren = {
  AuthenticatedGovLogsRoute: AuthenticatedGovLogsRoute,
  AuthenticatedGovStudentsRoute: AuthenticatedGovStudentsRoute,
  AuthenticatedGovIndexRoute: AuthenticatedGovIndexRoute,
}

const AuthenticatedGovRouteWithChildren =
  AuthenticatedGovRoute._addFileChildren(AuthenticatedGovRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGovRoute: typeof AuthenticatedGovRouteWithChildren
  AuthenticatedSchoolRoute: typeof AuthenticatedSchoolRoute
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGovRoute: AuthenticatedGovRouteWithChildren,
  AuthenticatedSchoolRoute: AuthenticatedSchoolRoute,
  AuthenticatedStudentRoute: AuthenticatedStudentRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
